spring:
  application:
    name: prices
  datasource:
    url: jdbc:h2:mem:prices
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect