openapi: 3.0.3
info:
  title: The Price Evaluator API
  description: Prices evaluator API developed using an API First approach, Hexagonal architecture and DDD.
  version: 0.0.1
servers:
  - url: https://localhost:8080/api
tags:
  - name: Prices API
    description: API to return the correct price for a particular product, moment in time and for a brand.
paths:
  /api/prices/getValidPrice:
    get:
      summary: Get applicable price for a product
      description: Get applicable price for a product in a particular date and for a brand.
      operationId: getValidPrice
      parameters:
        - in: query
          name: applicabilityDate
          schema:
            type: string
            format: date-time
          required: true
          description: The date to check the price for
        - in: query
          name: productId
          schema:
            type: string
          required: true
          description: The ID of the product
        - in: query
          name: brandId
          schema:
            type: string
          required: true
      responses:
        200:
          description: Applicable price found!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidPriceResponse'
        404:
          description: Price not found for given parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceNotFoundError'
components:
  schemas:
    ValidPriceResponse:
      type: object
      properties:
        productId:
          type: string
        brandId:
          type: string
        priceListId:
          type: string
        validityPeriod:
          type: string
        validPrice:
          type: string
    PriceNotFoundError:
      type: object
      properties:
        message:
          type: string